<a href="https://colab.research.google.com/github/wonjae124/2021_Lab_project/blob/main/CIFAR10_split_dataset_with_transform_torch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import torch
import cv2
import numpy
import matplotlib.pyplot as plt
from torchvision import datasets, transforms
from torch.utils.data import DataLoader


In [15]:
tr_dataset = datasets.CIFAR10(root = './data', train=True,
                                  download=True, transform = transforms.ToTensor())

test_dataset = datasets.CIFAR10(root='./data', train=False, download=True, transform= transforms.ToTensor())

tr_subset, val_subset = torch.utils.data.random_split(tr_dataset, [40000,10000], generator=torch.Generator().manual_seed(1))


Files already downloaded and verified
Files already downloaded and verified


In [56]:
tr_dataloader = DataLoader(tr_subset, batch_size = 32)
tr_dataloader_iter = iter(tr_dataloader)
data, target = tr_dataloader_iter.next()

In [63]:
print(data[3].numpy().shape)

#ㄷ

(3, 32, 32)


In [39]:
tr_subset_arr = tr_dataset.numpy()

AttributeError: ignored

In [21]:
len(tr_subset)

40000

In [16]:
len(val_subset)

10000

In [18]:
tr_subset

In [20]:
tr_subset.split()

AttributeError: ignored

In [72]:
print(tr_subset.indices.ndim)

AttributeError: ignored

In [87]:
X_train_set = torch.tensor(tr_subset.dataset.data[tr_subset.indices])
Y_train_set = torch.tensor(tr_subset.dataset.targets[tr_subset.indices])
X_val_set = val_subset.dataset.data[val_subset.indices]
Y_val_set = val_subset.dataset.targets[val_subset.indices]

train_loader = torch.utils.data.DataLoader(tr_subset, batch_size=batch_size)
valid_loader = torch.utils.data.DataLoader(val_subset, batch_size=batch_size)

TypeError: ignored

In [91]:
tr_subset.dataset.targets = torch.tensor(tr_subset.dataset.targets)

In [92]:
Y_train_set = torch.tensor(tr_subset.dataset.targets[tr_subset.indices])


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """Entry point for launching an IPython kernel.


In [93]:
Y_train_set

tensor([0, 1, 6,  ..., 1, 7, 4])

In [90]:
tr_subset.dataset.targets

[6,
 9,
 9,
 4,
 1,
 1,
 2,
 7,
 8,
 3,
 4,
 7,
 7,
 2,
 9,
 9,
 9,
 3,
 2,
 6,
 4,
 3,
 6,
 6,
 2,
 6,
 3,
 5,
 4,
 0,
 0,
 9,
 1,
 3,
 4,
 0,
 3,
 7,
 3,
 3,
 5,
 2,
 2,
 7,
 1,
 1,
 1,
 2,
 2,
 0,
 9,
 5,
 7,
 9,
 2,
 2,
 5,
 2,
 4,
 3,
 1,
 1,
 8,
 2,
 1,
 1,
 4,
 9,
 7,
 8,
 5,
 9,
 6,
 7,
 3,
 1,
 9,
 0,
 3,
 1,
 3,
 5,
 4,
 5,
 7,
 7,
 4,
 7,
 9,
 4,
 2,
 3,
 8,
 0,
 1,
 6,
 1,
 1,
 4,
 1,
 8,
 3,
 9,
 6,
 6,
 1,
 8,
 5,
 2,
 9,
 9,
 8,
 1,
 7,
 7,
 0,
 0,
 6,
 9,
 1,
 2,
 2,
 9,
 2,
 6,
 6,
 1,
 9,
 5,
 0,
 4,
 7,
 6,
 7,
 1,
 8,
 1,
 1,
 2,
 8,
 1,
 3,
 3,
 6,
 2,
 4,
 9,
 9,
 5,
 4,
 3,
 6,
 7,
 4,
 6,
 8,
 5,
 5,
 4,
 3,
 1,
 8,
 4,
 7,
 6,
 0,
 9,
 5,
 1,
 3,
 8,
 2,
 7,
 5,
 3,
 4,
 1,
 5,
 7,
 0,
 4,
 7,
 5,
 5,
 1,
 0,
 9,
 6,
 9,
 0,
 8,
 7,
 8,
 8,
 2,
 5,
 2,
 3,
 5,
 0,
 6,
 1,
 9,
 3,
 6,
 9,
 1,
 3,
 9,
 6,
 6,
 7,
 1,
 0,
 9,
 5,
 8,
 5,
 2,
 9,
 0,
 8,
 8,
 0,
 6,
 9,
 1,
 1,
 6,
 3,
 7,
 6,
 6,
 0,
 6,
 6,
 1,
 7,
 1,
 5,
 8,
 3,
 6,
 6,
 8,
 6,
 8,
 4,
 6,
 6,


In [82]:
print(X_train_set)

tensor([[[[ 89, 122, 179],
          [ 88, 121, 177],
          [ 87, 122, 178],
          ...,
          [113, 144, 193],
          [111, 143, 192],
          [110, 144, 192]],

         [[ 92, 124, 182],
          [ 91, 125, 181],
          [ 90, 126, 181],
          ...,
          [119, 151, 200],
          [116, 148, 197],
          [116, 150, 198]],

         [[ 94, 128, 185],
          [ 92, 128, 184],
          [ 91, 129, 184],
          ...,
          [123, 158, 203],
          [121, 156, 202],
          [123, 156, 202]],

         ...,

         [[236, 236, 231],
          [219, 221, 219],
          [165, 173, 185],
          ...,
          [ 91,  97, 118],
          [ 89,  95, 115],
          [ 89,  95, 112]],

         [[252, 252, 247],
          [238, 239, 238],
          [227, 229, 232],
          ...,
          [200, 201, 205],
          [216, 217, 220],
          [214, 215, 219]],

         [[255, 255, 255],
          [253, 254, 251],
          [255, 255, 253],
         

In [76]:

print( torch.tensor(tr_subset.dataset.targets))

tensor([6, 9, 9,  ..., 9, 1, 1])


In [44]:
print(len(X_train_set))

40000


In [34]:
dataset_iter = iter(tr_subset)
for indices in batch_sampler:
    yield collate_fn([next(dataset_iter) for _ in indices])

SyntaxError: ignored

In [ ]:
train_set_arr = X_train_set.numpy() #numpy 자료형(ndarray) 변환
val_set_arr = X_val_set.numpy()