<a href="https://colab.research.google.com/github/wonjae124/2021_Lab_project/blob/main/pytorch_tensor_tutorial1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [110]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [111]:
cd /content/drive/MyDrive/model/example

/content/drive/MyDrive/model/example


In [113]:
import numpy as np

In [114]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [115]:
print('Rank of: ', t.ndim) #벡터 차원. 1이면 벡터, 2이면 2차원 행렬, 3차원이면 3차원 텐서
print('Shape of: ', t.shape) #벡터의 크기. 벡터의 크기가 (7,)이면 1X7의 크기를 가지는 벡터 (2,3)이면 2X3크기의 2D 텐서

Rank of:  1
Shape of:  (7,)


In [116]:
print('t[0] t[1] t[2] = ', t[0], t[1], t[-1])

t[0] t[1] t[2] =  0.0 1.0 6.0


In [117]:
print(t[2:5],t[4:-1])

[2. 3. 4.] [4. 5.]


In [118]:
print(t[:2],t[3:])

[0. 1.] [3. 4. 5. 6.]


#2D numpy

In [119]:
t = np.array([[1., 2., 3.],[4., 5., 6.,],[7., 8., 9.],[10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [120]:
print(t.ndim)  #차원
print(t.shape) #크기

2
(4, 3)


#Tensor in Pytorch
numpy와 크기값을 측정하는 shape함수 동일
그러나,
numpy는 size()함수 없음

In [121]:
import torch

In [122]:
t = torch.FloatTensor([0., 1., 2., 3. ,4. ,5. ,6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [123]:
print(t.dim())
print(t.shape)
print(t.size())

1
torch.Size([7])
torch.Size([7])


In [124]:
print(t[0], t[1], t[-1]) #인덱스 접근
print(t[2:5], t[4:-1])   #슬라이싱 -1까지면 마지막 원소는 포함하지 않는다.
print(t[:2], t[3:])      #슬라이싱

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


#1D with Pytorch

In [125]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                       ])
t

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [126]:
print(t.dim())
print(t.shape)

2
torch.Size([4, 3])


In [127]:
print(t[:,1]) # 첫차원(모든 행)의 두번째 차원(두 번째 열)을 보여준다.
print(t[:,1].size())

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [128]:
print(t[0,:]) #첫 번째 행의 모든 열값을 보여준다.
print(t[0,:].size())

tensor([1., 2., 3.])
torch.Size([3])


In [129]:
print(t[:, :-1]) #첫 차원(모든 행)의 두 번째 차원(마지막 열 전까지)을 출력
print(t[:, :-1].size())

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])
torch.Size([4, 2])


#브로드 캐스팅(자동으로 크기를 맞추어서 연산 수행

In [130]:
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1+m2)

tensor([[5., 5.]])


In [131]:
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3],[4]])
print(m1+m2)

tensor([[4., 5.],
        [5., 6.]])


In [132]:
m3 = torch.FloatTensor([1,2])
m3.dim()

1

# 행렬 곱셈  .matmul
# 원소별 곱셈 .mul (element-wise)

In [133]:
m1 = torch.FloatTensor([[1,2],[3, 4]])
m2 = torch.FloatTensor([[1],[2]])
print(m1.shape)
print(m2.shape)
print(m1.matmul(m2)) # m1Xm2

torch.Size([2, 2])
torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [134]:
m1 = torch.FloatTensor([[1,2],[3, 4]])
m2 = torch.FloatTensor([[1],[2]])
print(m1*m2)
print(m1.mul(m2))

tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


#평균

In [135]:
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [136]:
t = torch.FloatTensor([[1,2],[3,4],[5,6]])
print(t)
print(t.shape)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
torch.Size([3, 2])


In [137]:
print(t.mean())

tensor(3.5000)


In [138]:
print(t.mean(dim=0)) #첫 번째 차원(행)을 제거한다. 벡터가 된다. 1X2로 말이다.
print(t.mean(dim=0).shape)

tensor([3., 4.])
torch.Size([2])


In [139]:
print(t.mean(dim=1)) #두 번째 차원(열)을 제거한다. 사실상 3X1이다.
print(t.mean(dim=1).shape)

tensor([1.5000, 3.5000, 5.5000])
torch.Size([3])


In [140]:
t = torch.FloatTensor([[1,2],[3,4],[5,6]])
t

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

#덧셈

In [141]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(21.)
tensor([ 9., 12.])
tensor([ 3.,  7., 11.])
tensor([ 3.,  7., 11.])


#MAX와 Argmax

In [142]:
t = torch.FloatTensor([[1,2], [3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [143]:
print(t.max())

tensor(4.)


In [144]:
print(t.max(dim=0)) #return two values : max and argmax(최대값 전달인자)

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [145]:
print(t.max(dim=0)[0]) #첫 번째 차운(행을 제거)한 상태에서 리턴 값 중 첫 번째 값(max)
print(t.max(dim=0)[1])

tensor([3., 4.])
tensor([1, 1])


In [146]:
print(t.max(dim=1)) #두 번째 차원(열)을 제거함
print(t.max(dim=-1)) 

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
