<a href="https://colab.research.google.com/github/wonjae124/2021_Lab_project/blob/main/tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [3]:
x=torch.empty(5,4) #5X4행렬 생성
x

tensor([[-2.7949e+12,  3.0872e-41,  7.0065e-44,  7.0065e-44],
        [ 6.3058e-44,  6.7262e-44,  6.8664e-44,  6.3058e-44],
        [ 6.8664e-44,  7.0065e-44,  1.1771e-43,  6.7262e-44],
        [ 7.1466e-44,  8.1275e-44,  6.8664e-44,  7.0065e-44],
        [ 8.1275e-44,  6.8664e-44,  7.8473e-44,  6.4460e-44]])

In [4]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [5]:
torch.rand(5,6)

tensor([[0.8931, 0.4215, 0.9316, 0.4220, 0.9579, 0.8378],
        [0.7830, 0.7227, 0.5201, 0.7596, 0.6530, 0.9941],
        [0.1806, 0.0900, 0.9726, 0.9557, 0.3453, 0.8450],
        [0.7004, 0.5211, 0.6899, 0.4406, 0.6634, 0.2167],
        [0.5167, 0.0286, 0.7621, 0.6767, 0.6105, 0.4744]])

In [6]:
l = [1,2,3]
a = [[1,2,3],[4,5,6]]
print(torch.tensor(l))
print(torch.tensor(a))

tensor([1, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [7]:
x.size()

torch.Size([5, 4])

In [8]:
print(x.size())

torch.Size([5, 4])


In [9]:
type(x)

torch.Tensor

In [27]:
y=torch.ones(2,2)
y

tensor([[1., 1.],
        [1., 1.]])

In [29]:
y.add(x) #아직 y의 값이 할당되지는 않았음. y=y.add(x)로 해야지 초기화 완료 됨.

tensor([[2., 2.],
        [2., 2.]])

In [30]:
y

tensor([[1., 1.],
        [1., 1.]])

In [31]:
torch.add(y,y)#y의 값이 할당이 여전히 안 됨.

tensor([[2., 2.],
        [2., 2.]])

In [32]:
y

tensor([[1., 1.],
        [1., 1.]])

In [41]:
#텐서의 크기를 변화하는 방법
#2차원 행렬 정의
x=torch.rand(8,8)
x.size()

torch.Size([8, 8])

In [40]:
x
@대괄호가 2개 있다.

tensor([[0.2203, 0.8508, 0.7299, 0.8461, 0.0704, 0.1360, 0.0674, 0.3223],
        [0.3222, 0.1972, 0.0371, 0.8087, 0.5769, 0.5631, 0.7961, 0.1337],
        [0.9340, 0.5137, 0.1116, 0.4120, 0.3439, 0.3355, 0.3007, 0.0522],
        [0.1076, 0.0865, 0.1845, 0.2281, 0.8093, 0.8173, 0.3745, 0.0983],
        [0.5558, 0.1974, 0.1180, 0.0395, 0.0373, 0.0281, 0.8786, 0.5047],
        [0.7126, 0.2811, 0.8241, 0.6172, 0.4034, 0.3921, 0.4733, 0.7200],
        [0.6035, 0.0552, 0.5416, 0.6060, 0.7862, 0.4375, 0.3516, 0.3764],
        [0.4842, 0.8945, 0.3469, 0.0074, 0.2735, 0.2164, 0.0786, 0.3296]])

In [42]:
#2차원 행렬을 1차원 행렬로 변환
a=x.view(64) 
a.size()

torch.Size([64])

In [44]:
a #1차원 행렬 확인하기

tensor([0.2660, 0.5387, 0.3802, 0.5905, 0.8140, 0.4642, 0.3407, 0.2346, 0.8318,
        0.7161, 0.2358, 0.9385, 0.7554, 0.8523, 0.4284, 0.8660, 0.2934, 0.2116,
        0.3904, 0.9204, 0.0280, 0.4235, 0.8480, 0.7623, 0.2866, 0.1994, 0.6040,
        0.7686, 0.2135, 0.9468, 0.5499, 0.0392, 0.8537, 0.4795, 0.4995, 0.3011,
        0.2095, 0.2016, 0.9566, 0.8395, 0.2820, 0.1938, 0.8641, 0.0308, 0.3613,
        0.5679, 0.2368, 0.6016, 0.5940, 0.0240, 0.2653, 0.3498, 0.0853, 0.6009,
        0.9996, 0.3026, 0.1424, 0.9828, 0.9827, 0.0361, 0.6046, 0.4050, 0.9248,
        0.5725])

In [51]:
#2차원 행렬을 3차원 행렬로 변환
b=x.view(-1,4,4) #-1은 모든 원서를 다 표현하게끔 컴퓨터가 자동(알아서)으로 차원을 결정한다.
b.size()

RuntimeError: ignored

In [46]:
#3차원 행렬 확인하기
#대괄호가 3개 있다.
b

tensor([[[0.2660, 0.5387, 0.3802, 0.5905],
         [0.8140, 0.4642, 0.3407, 0.2346],
         [0.8318, 0.7161, 0.2358, 0.9385],
         [0.7554, 0.8523, 0.4284, 0.8660]],

        [[0.2934, 0.2116, 0.3904, 0.9204],
         [0.0280, 0.4235, 0.8480, 0.7623],
         [0.2866, 0.1994, 0.6040, 0.7686],
         [0.2135, 0.9468, 0.5499, 0.0392]],

        [[0.8537, 0.4795, 0.4995, 0.3011],
         [0.2095, 0.2016, 0.9566, 0.8395],
         [0.2820, 0.1938, 0.8641, 0.0308],
         [0.3613, 0.5679, 0.2368, 0.6016]],

        [[0.5940, 0.0240, 0.2653, 0.3498],
         [0.0853, 0.6009, 0.9996, 0.3026],
         [0.1424, 0.9828, 0.9827, 0.0361],
         [0.6046, 0.4050, 0.9248, 0.5725]]])

In [49]:
#단일 텐서에서 값을 추출하기
x = torch.ones(5)
x

tensor([1., 1., 1., 1., 1.])

In [48]:
x.item() 
#단일 값을 뽑아내기 위해서는 item함수를 사용한다.


1.0

In [ ]:
#############단일 이미지 값을 뽑아내는 방법을 알아보자(2차원 행렬이 필요하겠지?)###############