<a href="https://colab.research.google.com/github/wonjae124/2021_Lab_project/blob/main/torch_cat_size.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#torch cat은 주어진 차원을 기준으로 주어진 텐서를 붙인다.

In [11]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [12]:
cd /content/drive/MyDrive/model/example

/content/drive/MyDrive/model/example


In [13]:
!git clone https://github.com/wonjae124/2021_Lab_project.git

Cloning into '2021_Lab_project'...
remote: Enumerating objects: 114, done.
remote: Counting objects: 100% (114/114), done.
remote: Compressing objects: 100% (112/112), done.
remote: Total 114 (delta 49), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (114/114), 18.39 MiB | 10.44 MiB/s, done.
Resolving deltas: 100% (49/49), done.


In [2]:
import torch

batch_size, N , K = 3,10,256

x = torch.rand(batch_size, N, K) # tensor를 반환하는 rand함수. [M,N,K]로 N은 세로 height, K는 폭 width이다. 
y = torch.rand(batch_size, N, K)

print(x.size()) #dimension은 3,10,256이다.
print(y.size()) #dimension은 3,10,256이다.

output1 = torch.cat([x,y],1) #10+10 = 20, 3,20,256
output2 = torch.cat([x,y],2) #256+256=512, 3,10,512이다.
output3 = torch.cat([x,y]) #tensor란 파이썬에서의 배열이다.torch.cat(tensor,dim=0,*,out=None)이다. dim의 default=0으로 첫 번째 차원인 것이다.
                           #cat(x,y)를 하면 dim이 int가 아니므로 오류 발생한다. 따라서 배열로 만들게끔 x,y를 []안에 묶어야 한다.

print('##############')
print(x.size(),'\n')
print(output1.size(),'\n')
print(output2.size(),'\n')
print(output3.size(),'\n')

torch.Size([3, 10, 256])
torch.Size([3, 10, 256])
##############
torch.Size([3, 10, 256]) 

torch.Size([3, 20, 256]) 

torch.Size([3, 10, 512]) 

torch.Size([6, 10, 256]) 



In [3]:
t1 = torch.tensor([[1,2],
                  [3,4]])
t2 = torch.tensor([[5,6],
                   [7,8]])

In [6]:
t1.size()

torch.Size([2, 2])

In [7]:
t3 = torch.cat([t1,t2],dim=0)
print(t3,'\n')
print(t3.size())

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]) 

torch.Size([4, 2])


In [8]:
t4 = torch.cat([t1, t2], dim=1)
print(t4,'\n')
print(t4.size())

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]]) 

torch.Size([2, 4])


#torch.stack은 새로운 차원을 생성한다.

In [9]:
t5 = torch.stack((t1, t2))
print(t5,'\n')
print(t5.size())

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]]) 

torch.Size([2, 2, 2])


In [ ]:
x1 = ['Ticks', 'Tock', 'Song']
x2 = ['Ticks', 'Tock', 'Song']
y = ['Ping', 'Pong']
x1.append(y) #append는 맨 끝에 새로운 객체로 추가한다. 리스트 형태로 추가 됬다.
x2.extend(y) #리스트(iterable) 끝에 가장 바깥쪽 항목으로 추가한다. 단, 추가는 interable 자료형만 가능함
print('x1:', x1)
print('x2:', x2)

x1: ['Ticks', 'Tock', 'Song', ['Ping', 'Pong']]
x2: ['Ticks', 'Tock', 'Song', 'Ping', 'Pong']


In [ ]:
#view(-1), tensor차원 풀기. 반환값 tensor임.
#view(n,-1)로 tensor차원 풀되, [nX]형태로 유지하기
t3 = torch.tensor([[1,2],[3,4],[5,6]]) #3X2
print(t3, '\n')
print(t3.size(),'\n\n')
print(t3.view(-1),'\n')
print(t3.view(-1).size(),'\n\n') #결과 차원은 6이다.
print(t3.view(1,-1),'\n')
print(t3.view(1,-1).size(),'\n\n') # 차원 [1X] 형태로 만듦. 결과는 1X6

출처 :https://technical-support.tistory.com/95

tensor([[1, 2],
        [3, 4],
        [5, 6]]) 

torch.Size([3, 2]) 


tensor([1, 2, 3, 4, 5, 6]) 

torch.Size([6]) 


tensor([[1, 2, 3, 4, 5, 6]]) 

torch.Size([1, 6]) 




In [ ]:
t2 = torch.tensor([1,2])